apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test7
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  lifecycle: experimental
  stack: node
  owner: group:dumdumorg
